name: Build and Deploy to Azure

on:
  push:
    branches: [ "main" ] # Dispara o deploy ao commitar na main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do c√≥digo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Rodar Testes
        run: dotnet test BlueCloudApi.Tests/BlueCloudApi.Tests.csproj

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push da Imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/blue-cloud-api:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy no Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'nome-do-seu-app-no-azure'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: '${{ secrets.DOCKERHUB_USERNAME }}/blue-cloud-api:latest'